//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReleaseManagement.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLEntryDetail
    {
        public int ID { get; set; }
        public string EnterpriseId { get; set; }
        public string TottNo { get; set; }
        public string TottDescription { get; set; }
        public Nullable<int> TaskTypeID { get; set; }
        public Nullable<decimal> TotalHrs { get; set; }
        public Nullable<int> RegionID { get; set; }
        public string TaskDate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<int> TottID { get; set; }
    
        public virtual TBLRegionMaster TBLRegionMaster { get; set; }
        public virtual TBLRegionMaster TBLRegionMaster1 { get; set; }
        public virtual TBLTaskTypeMaster TBLTaskTypeMaster { get; set; }
        public virtual TBLTaskTypeMaster TBLTaskTypeMaster1 { get; set; }
        public virtual TBLTOTTMaster TBLTOTTMaster { get; set; }
        public virtual TBLTOTTMaster TBLTOTTMaster1 { get; set; }
    }
}
