//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReleaseManagement.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLTaskTypeMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLTaskTypeMaster()
        {
            this.TBLEntryDetails = new HashSet<TBLEntryDetail>();
            this.TBLEntryDetails1 = new HashSet<TBLEntryDetail>();
            this.TBLTOTTMasters = new HashSet<TBLTOTTMaster>();
        }
    
        public int TaskTypeID { get; set; }
        public string TaskType { get; set; }
        public bool isTottTask { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLEntryDetail> TBLEntryDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLEntryDetail> TBLEntryDetails1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLTOTTMaster> TBLTOTTMasters { get; set; }
    }
}
