//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReleaseManagement.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLUsersDetail
    {
        public int ID { get; set; }
        public string EnterpriseId { get; set; }
        public string password { get; set; }
        public string EnterpriseName { get; set; }
        public Nullable<int> RoleID { get; set; }
        public string EmailId { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public byte[] UserPassword { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual TBLRoleMaster TBLRoleMaster { get; set; }
        public virtual TBLRoleMaster TBLRoleMaster1 { get; set; }
    }
}
